# Generated by Django 5.1 on 2024-08-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAWEBMAIN', '0004_team_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_top',
            name='flag_url',
            field=models.CharField(max_length=10),
        ),
    ]
