# Generated by Django 5.1 on 2024-08-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAWEBMAIN', '0006_alter_team_top_flag_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_top',
            name='flag_url',
            field=models.CharField(max_length=3),
        ),
    ]
